<?php

/**
 * @file
 * Primary module hooks for Tidy Local Tasks module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme_registry_alter().
 */
function tidy_local_tasks_theme_registry_alter(&$theme_registry) {
  if (!empty($theme_registry['menu_local_tasks'])) {
    $module_path = \Drupal::service('extension.list.module')->getPath('tidy_local_tasks');
    $theme_registry['menu_local_tasks']['path'] = $module_path . '/templates/navigation';
  }
}
