<?php

/**
 * @file
 * Primary module hooks for Tidy Local Tasks module.
 */

/**
 * Implements hook_theme().
 */
function tidy_local_tasks_theme($existing, $type, $theme, $path) {
  // Provide an alternate theme hook for local tasks.
  return [
    'tidy_local_tasks' => [
      'variables' => [
        'primary' => [],
        'secondary' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function tidy_local_tasks_theme_suggestions_menu_local_tasks(array $variables) {
  // IF we're not on the admin side, apply the alternate theme hook we created
  // in tidy_local_tasks_theme().
  $active_theme = \Drupal::theme()->getActiveTheme()->getName();
  $admin_theme = \Drupal::config('system.theme')->get('admin');
  if ($active_theme == $admin_theme) {
    return [];
  }
  return ['tidy_local_tasks'];
}
